/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.sportradar;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ScoreboardTest {
    @Test void someLibraryMethodReturnsTrue() {

    }
}
